framework:
    workflows:
        booking:
            type: 'workflow'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - App\Entity\SequenceContainer
            places:
                - step1
                - confirmed
            transitions:
                to_confirmed:
                    from: step1
                    to:   confirmed
